---
global:
  data:
    domain: global.local
    asn: 1

eu:
  data:
    asn: 65100
    dns_servers:
      - 172.16.1.1
      - 172.16.1.2
    ntp_peers:
      - 10.10.1.1
      - 10.10.2.2
    ntp_servers:
      - 172.16.1.100
      - 172.16.1.10

juniper:
  data:
    local_users:
      - salt:
          class: super-user
          password: $6$mO/LQ5gy$JzpleTjLTLPIG/sKz62pB/M6WMCtM1ojrpNcHKUBlBsjp15m8BudeVyab.UgZj1DgV4qcMV1CPklc/rDo2fNw0
          uid: 2000
      - inetzero:
          class: supervisor
          password: $6$KW18QR0JonVPopSl$oCj1nnhiqOv.DnJgvKOGv0PAmoFL3N.0vrKJxVRlQOgrym2V5VPBw.y80aX0er165Y0LXj.4er4hoUIR64T5t/
          uid: 2001
    classes:
      - supervisor



bma:
  groups:
    - eu
    - global

cmh:
  data:
    asn: 65000

