---
core:
  num_workers: 1

inventory:
  plugin: nornir.plugins.inventory.netbox.NBInventory
  options:
    nb_url: "https://192.168.122.151"
    nb_token: "144de785b9a868ae7cc2d62a55841273cd28182e"
    ssl_verify: False
  transform_function: "helpers.adapt.more_data"
